const ActionTypes = {
  FETCH_QUOTES_REQUEST: 'FETCH_QUOTES_REQUEST',
  FETCH_QUOTES_SUCCESS: 'FETCH_QUOTES_SUCCESS',
  FETCH_QUOTES_FAILURE: 'FETCH_QUOTES_FAILURE',
  RESET_QUOTES: 'RESET_QUOTES'
}

export default ActionTypes
